### ISSUE TITLE
does not work in unity 2019.2 

### ISSUE THREAD

**Issue by pachermann** [Plattar/Unity-glTF-Exporter#1]
using Ionic.Zip; does make some problems can't use it.
could you fix it?

**Comment by DavidArayan** [comment]
Hello @pachermann,

This repository is no longer being maintained, as per the ReadMe please use the new exporter we have developed at [https://github.com/Plattar/gltf-exporter](https://github.com/Plattar/gltf-exporter).

Cheers!
